//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stockie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentCard()
        {
            this.PaymentOptions = new HashSet<PaymentOption>();
        }
    
        public string Id { get; set; }
        public string CardNumber { get; set; }
        public string CardHolder { get; set; }
        public string CVV { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string CardType { get; set; }
        public int Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentOption> PaymentOptions { get; set; }
    }
}
